config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :user

  scope '(:locale)', locale: /jp/ do
    root to: 'pages#landing'
    get '/explorer/:list_name', to: 'explorer#load', as: :explorer
    get '/dashboard', to: 'dashboard#load', as: :dashboard
    resources :lists, only: [:index]
  end

  # API routing
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      get '/lists/:list_name/regions', to: 'lists#list_regions'
      get '/lists/:list_name/geojson', to: 'lists#fetch_geojson'
      get '/lists/:list_name/bounds', to: 'lists#fetch_map_bounds'
      get '/:list_name/regions/:region_id', to: 'lists#region_geojson'
    end
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<%
=begin%>
  This view isn't currently used as it was moved to the react app, but it's not
  been deleted yet because I might still use it somewhere else.
<%
=end%>
<div class="navbar">
  <div class="left-group left-top-nav">
    <%= link_to root_path do %>
      <div class="logo-holder">
        <%= image_tag "logo.png", class: "nav-logo" %>
      </div>
    <% end %>
  </div>
  <div class="center-group center-top-nav">
    <i class="fas fa-mountain nav-icon"></i>
    <i class="fas fa-user nav-icon"></i>
    <%= link_to lists_path(1) do %>
      <i class="fas fa-scroll nav-icon"></i>
    <% end %>
    <i class="fas fa-home nav-icon"></i>
  </div>
  <div class="right-group right-top-nav">
    <div class="set-lang">
    <% if I18n.locale == I18n.default_locale %>
      <%= link_to "日", { locale: 'jp' } %>
    <% else %>
      <%= link_to "En", { locale: nil } %>
    <%end%>
    </div>
  </div>
</div>